// Copyright 2025 Chuvadi Contributors
// SPDX-License-Identifier: Apache-2.0
// SPEC:  PDF 32000-1:2008 §9.10 — Extraction of text content
// PHASE: Phase 1 — Chuvadi.Pdf.Text
// Layout-aware text extraction: groups by line, sorts by X position.

using System;
using System.Collections.Generic;
using System.Text;
using Chuvadi.Pdf.Content;

namespace Chuvadi.Pdf.Text;

/// <summary>
/// Extracts text from <see cref="TextFragment"/> objects by reconstructing
/// the visual reading order: group by line (Y position), sort by column (X position).
/// </summary>
/// <remarks>
/// This strategy is more accurate than <see cref="OperatorExtractor"/> for PDFs
/// where text is not written in reading order in the content stream —
/// for example, multi-column layouts, tables, or PDFs generated by page-layout
/// software that writes content in draw order rather than reading order.
///
/// Algorithm:
/// <list type="number">
///   <item>Group fragments into lines: two fragments are on the same line when
///   their Y difference is less than half the average font size of the line.</item>
///   <item>Sort lines by descending Y (PDF Y increases upward, so highest Y = top).</item>
///   <item>Within each line, sort fragments by ascending X.</item>
///   <item>Insert spaces between fragments based on X gaps.</item>
/// </list>
///
/// PDF 32000-1:2008 §9.10 — Extraction of text content.
/// </remarks>
public sealed class LayoutExtractor
{
    /// <summary>
    /// Converts a list of text fragments to a plain text string
    /// using layout-aware line grouping and X-sorted reading order.
    /// </summary>
    /// <param name="fragments">Fragments from <see cref="ContentStreamParser"/>.</param>
    /// <returns>The extracted text with spaces and line breaks inserted.</returns>
    public string Extract(List<TextFragment> fragments)
    {
        if (fragments is null)
        {
            throw new ArgumentNullException(nameof(fragments));
        }

        if (fragments.Count == 0)
        {
            return string.Empty;
        }

        // Step 1: group fragments into lines.
        List<List<TextFragment>> lines = GroupIntoLines(fragments);

        // Step 2: sort lines top-to-bottom (descending Y in PDF space).
        lines.Sort((a, b) => b[0].Y.CompareTo(a[0].Y));

        // Step 3: within each line, sort left-to-right (ascending X).
        foreach (List<TextFragment> line in lines)
        {
            line.Sort((a, b) => a.X.CompareTo(b.X));
        }

        // Step 4: assemble output.
        StringBuilder sb = new StringBuilder();

        for (int lineIdx = 0; lineIdx < lines.Count; lineIdx++)
        {
            List<TextFragment> line = lines[lineIdx];

            if (lineIdx > 0)
            {
                sb.AppendLine();
            }

            TextFragment prev = line[0];
            sb.Append(prev.Text);

            for (int i = 1; i < line.Count; i++)
            {
                TextFragment current = line[i];
                double xGap = current.X - (prev.X + EstimateWidth(prev));

                // Insert a separating space on a positional gap — but not when
                // the fragments already carry one (many writers end each
                // word-run with an explicit trailing space; width estimation
                // errors on such runs would otherwise produce double spaces).
                bool alreadySeparated =
                    (prev.Text.Length > 0 && prev.Text[prev.Text.Length - 1] == ' ')
                    || (current.Text.Length > 0 && current.Text[0] == ' ');

                if (xGap > prev.FontSize * 0.3 && !alreadySeparated)
                {
                    sb.Append(' ');
                }

                sb.Append(current.Text);
                prev = current;
            }
        }

        return sb.ToString().Trim();
    }

    // ── Private ───────────────────────────────────────────────────────────

    private static List<List<TextFragment>> GroupIntoLines(List<TextFragment> fragments)
    {
        List<List<TextFragment>> lines = new List<List<TextFragment>>();

        foreach (TextFragment fragment in fragments)
        {
            bool placed = false;

            foreach (List<TextFragment> line in lines)
            {
                double lineY = AverageY(line);
                double threshold = AverageFontSize(line) * 0.5;

                if (Math.Abs(fragment.Y - lineY) <= threshold)
                {
                    line.Add(fragment);
                    placed = true;
                    break;
                }
            }

            if (!placed)
            {
                lines.Add(new List<TextFragment> { fragment });
            }
        }

        return lines;
    }

    private static double AverageY(List<TextFragment> line)
    {
        double sum = 0;

        foreach (TextFragment f in line)
        {
            sum += f.Y;
        }

        return sum / line.Count;
    }

    private static double AverageFontSize(List<TextFragment> line)
    {
        double sum = 0;

        foreach (TextFragment f in line)
        {
            sum += f.FontSize;
        }

        return sum / line.Count;
    }

    private static double EstimateWidth(TextFragment fragment)
    {
        return fragment.Text.Length * fragment.FontSize * 0.6;
    }
}
